"""Authentication routes: login, refresh, me."""

from __future__ import annotations

import os

from fastapi import APIRouter, Depends, HTTPException, Request, status
from fastapi.responses import JSONResponse

from ava.console import auth
from ava.console.local_accounts import LOCAL_OWNER_USERNAME
from ava.console.models import LoginRequest, LoginResponse, UserInfo
from ava.console.middleware import get_client_ip

router = APIRouter(prefix="/api/auth", tags=["auth"])


@router.post("/login", response_model=LoginResponse)
async def login(body: LoginRequest, request: Request):
    from ava.console.app import get_services

    svc = get_services()
    user = svc.users.verify_password(body.username, body.password)
    if not user:
        svc.audit.log(
            user=body.username, role="unknown", action="auth.login_failed",
            target="", ip=get_client_ip(request),
        )
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid credentials")

    token = auth.create_access_token({"sub": user.username, "role": user.role, "created_at": user.created_at})
    svc.audit.log(
        user=user.username, role=user.role, action="auth.login",
        target="", ip=get_client_ip(request),
    )
    response = JSONResponse(LoginResponse(user=user).model_dump())
    auth.set_session_cookie(response, token, request)
    return response


@router.post("/refresh", response_model=LoginResponse)
async def refresh(request: Request, user: UserInfo = Depends(auth.get_current_user)):
    token = auth.create_access_token({"sub": user.username, "role": user.role, "created_at": user.created_at})
    response = JSONResponse(LoginResponse(user=user).model_dump())
    auth.set_session_cookie(response, token, request)
    return response


@router.get("/me", response_model=UserInfo)
async def me(user: UserInfo = Depends(auth.get_current_user)):
    return user


@router.post("/logout")
async def logout():
    response = JSONResponse({"ok": True})
    auth.clear_session_cookie(response)
    return response


@router.post("/desktop-session", response_model=LoginResponse)
async def desktop_session(request: Request):
    """Issue an owner session for the Electron desktop shell.

    Gated by ``AVA_DESKTOP=1`` so this route is unreachable from a server
    process not launched by the desktop wrapper. The shared secret is
    generated by Electron Main and injected via env at sidecar spawn.
    """
    from ava.console.app import get_services

    if os.environ.get("AVA_DESKTOP") != "1":
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Not Found")

    presented = request.headers.get("x-ava-desktop-token", "")
    if not auth.verify_desktop_token(presented):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid desktop token")

    svc = get_services()
    user = svc.users.get_user(LOCAL_OWNER_USERNAME)
    if user is None or user.role != "owner":
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR, detail="Owner account missing")

    token = auth.create_access_token({"sub": user.username, "role": user.role, "created_at": user.created_at})
    svc.audit.log(
        user=user.username, role=user.role, action="auth.desktop_session",
        target="", ip=get_client_ip(request),
    )
    response = JSONResponse(LoginResponse(user=user).model_dump())
    auth.set_session_cookie(response, token, request)
    return response
