#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_PATH="${1:-${REPO_ROOT}/electron/dist/Ava-darwin-arm64/Ava.app}"

fail() {
  echo "verify-desktop-setup-surface: $*" >&2
  exit 1
}

require_file() {
  local file="$1"
  [[ -f "${file}" ]] || fail "missing file: ${file}"
}

require_contains() {
  local file="$1"
  local needle="$2"
  grep -Fq -- "${needle}" "${file}" || fail "${file} missing: ${needle}"
}

MAIN="${REPO_ROOT}/electron/main.mjs"
PRELOAD="${REPO_ROOT}/electron/preload.cjs"
SETUP="${REPO_ROOT}/electron/setup.html"
DESKTOP_CONFIG="${REPO_ROOT}/electron/lib/desktop-config.mjs"
CORE_HEALTH="${REPO_ROOT}/electron/lib/core-health.mjs"
LAUNCH_ENV="${REPO_ROOT}/electron/lib/launch-env.mjs"
RUNTIME_MANIFEST="${REPO_ROOT}/electron/lib/runtime-manifest.mjs"
RUNTIME_MIRROR="${REPO_ROOT}/electron/lib/runtime-mirror.mjs"
BUILD_SCRIPT="${REPO_ROOT}/electron/scripts/build.mjs"
APP_ASAR="${APP_PATH}/Contents/Resources/app.asar"
PACKAGED_RUNTIME_MANIFEST="${APP_PATH}/Contents/Resources/ava-runtime-manifest.json"

require_file "${MAIN}"
require_file "${PRELOAD}"
require_file "${SETUP}"
require_file "${DESKTOP_CONFIG}"
require_file "${CORE_HEALTH}"
require_file "${LAUNCH_ENV}"
require_file "${RUNTIME_MANIFEST}"
require_file "${RUNTIME_MIRROR}"
require_file "${BUILD_SCRIPT}"
require_file "${APP_ASAR}"
require_file "${PACKAGED_RUNTIME_MANIFEST}"

require_contains "${MAIN}" "mainWindow.loadFile(path.join(__dirname, 'setup.html'))"
require_contains "${MAIN}" "const CORE_HEALTH_TIMEOUT_MS = 120_000"
require_contains "${MAIN}" "SETUP_LOAD_TIMEOUT_MS"
require_contains "${MAIN}" "did-finish-load"
require_contains "${MAIN}" "did-fail-load"
require_contains "${MAIN}" "clearTimeout(setupLoadTimeout)"
require_contains "${MAIN}" "dialog.showErrorBox('Ava setup failed to load'"
require_contains "${MAIN}" "function showFatalStartupError(error)"
require_contains "${MAIN}" "dialog.showErrorBox('Ava startup failed'"
require_contains "${MAIN}" ".catch(showFatalStartupError)"
require_contains "${MAIN}" "ipcMain.handle('ava:setNanobotRoot'"
require_contains "${MAIN}" "ipcMain.handle('ava:retryCore'"
require_contains "${MAIN}" "ipcMain.handle('ava:cancelBootstrap'"
require_contains "${MAIN}" "saveNanobotRoot(app.getPath('appData'), root)"
require_contains "${MAIN}" "validateNanobotRoot(nanobotRoot)"
require_contains "${MAIN}" "active.child.kill('SIGTERM')"
require_contains "${MAIN}" "active.child.kill('SIGKILL')"
require_contains "${MAIN}" "await stopAvaCore();"
require_contains "${MAIN}" "avaCoreProcess = null;"
require_contains "${MAIN}" "label: 'Help'"
require_contains "${MAIN}" "label: 'Edit'"
require_contains "${MAIN}" "label: 'View'"
require_contains "${MAIN}" "label: 'Window'"
require_contains "${MAIN}" "role: 'close'"
require_contains "${MAIN}" "label: 'Retry Core'"
require_contains "${MAIN}" "label: 'Open Logs'"
require_contains "${MAIN}" "label: 'Show Window'"
require_contains "${MAIN}" "Menu.setApplicationMenu(menu)"
require_contains "${MAIN}" "function ensureForegroundActivation()"
require_contains "${MAIN}" "app.setActivationPolicy('regular')"
require_contains "${MAIN}" "app.dock?.show?.()"
require_contains "${MAIN}" "function presentMainWindow(appWindow, reason)"
require_contains "${MAIN}" "appWindow.setSkipTaskbar(false)"
require_contains "${MAIN}" "appWindow.moveTop()"
require_contains "${MAIN}" "app.focus({ steal: true })"
require_contains "${MAIN}" "app.commandLine.appendSwitch('use-mock-keychain')"
require_contains "${MAIN}" "show: false"
require_contains "${MAIN}" "focusable: true"
require_contains "${MAIN}" "function createBootstrapWindow(config, { loadSetup = true } = {})"
require_contains "${MAIN}" "if (!loadSetup)"
require_contains "${MAIN}" "createBootstrapWindow(config, { loadSetup: !consoleLoaded })"
require_contains "${MAIN}" "presentMainWindow(mainWindow, 'setup loaded')"
require_contains "${MAIN}" 'presentMainWindow(mainWindow, `console loaded: ${reason}`)'
require_contains "${MAIN}" "await showMainWindow();"
require_contains "${MAIN}" "const TRAY_ICON_SIZE = 18;"
require_contains "${MAIN}" "image.resize({ width: TRAY_ICON_SIZE, height: TRAY_ICON_SIZE })"
require_contains "${MAIN}" "new Tray(trayImage)"
require_contains "${MAIN}" "globalShortcut.register('Control+Shift+A'"
require_contains "${MAIN}" "globalShortcut.unregisterAll()"
require_contains "${MAIN}" "ipcMain.handle('ava:setBadgeCount'"
require_contains "${MAIN}" "return { ok: false, error: 'invalid badge count' }"
require_contains "${MAIN}" "scheduleUpdateChecks();"
require_contains "${MAIN}" "const UPDATE_CHECK_INITIAL_DELAY_MS = 5 * 1000;"
require_contains "${MAIN}" "update check failed:"
require_contains "${MAIN}" "update notification shown for"
require_contains "${MAIN}" "if (process.platform !== 'darwin')"
require_contains "${MAIN}" "app.on('activate', () => {"
require_contains "${MAIN}" "const RING_BUFFER_BYTES = 256 * 1024"
require_contains "${MAIN}" "function appendRingBuffer(buffer, chunk, maxBytes = RING_BUFFER_BYTES)"
require_contains "${MAIN}" "stderrTail = appendRingBuffer(stderrTail, chunk)"
require_contains "${MAIN}" "detailParts.join('\\n\\n').slice(0, RING_BUFFER_BYTES)"
require_contains "${MAIN}" "buttons: ['Retry', 'Pick nanobot', 'Open logs', 'Quit']"
require_contains "${MAIN}" "from './lib/runtime-manifest.mjs'"
require_contains "${MAIN}" "from './lib/runtime-mirror.mjs'"
require_contains "${MAIN}" "readRuntimeManifestRepoRoot(runtimeManifestPaths(__dirname))"
require_contains "${MAIN}" "prepareRuntimeMirror({"
require_contains "${MAIN}" "appDataPath: app.getPath('userData')"
require_contains "${MAIN}" "const venvPythonPath = path.join(config.repoRoot, '.venv', 'bin', 'python')"
require_contains "${MAIN}" "const pythonPath = fs.realpathSync(venvPythonPath)"
require_contains "${MAIN}" "path.join(process.resourcesPath, 'ava-runtime')"
require_contains "${MAIN}" "spawn(pythonPath, ['-m', 'ava', 'gateway']"
require_contains "${MAIN}" "async function checkStartupInterfaces(config)"
require_contains "${MAIN}" "await waitForStartupInterfaces(config);"
require_contains "${MAIN}" "/api/auth/me"
require_contains "${MAIN}" "Ava auth interface returned HTTP"
require_contains "${MAIN}" "core_startup_timeout"
require_contains "${MAIN}" "Ava core did not become reachable within"

require_contains "${CORE_HEALTH}" "export function httpGetStatus(url, timeoutMs = 2_000)"
require_contains "${RUNTIME_MIRROR}" "export function prepareRuntimeMirror"
require_contains "${RUNTIME_MIRROR}" "runtime-mirror"
require_contains "${RUNTIME_MIRROR}" "function copyEntry"
require_contains "${RUNTIME_MIRROR}" "nanobot-checkout"

require_contains "${DESKTOP_CONFIG}" "export function validateNanobotRoot(root)"
require_contains "${DESKTOP_CONFIG}" "export function saveNanobotRoot(appDataPath, root"
require_contains "${DESKTOP_CONFIG}" "export function resolveNanobotCandidate"

require_contains "${LAUNCH_ENV}" "export function resolveLaunchPath"
require_contains "${LAUNCH_ENV}" "export function findExecutable(command, env)"
require_contains "${LAUNCH_ENV}" "export function venvSitePackages(repoRoot, pythonExecutable = '')"
require_contains "${LAUNCH_ENV}" "export function buildCoreEnv(config, nanobotRoot)"
require_contains "${LAUNCH_ENV}" "VIRTUAL_ENV: path.join(config.repoRoot, '.venv')"
require_contains "${LAUNCH_ENV}" "AVA_DESKTOP_CONSOLE_PORT: String(config.port)"
require_contains "${LAUNCH_ENV}" "AVA_DESKTOP_GATEWAY_PORT"
require_contains "${LAUNCH_ENV}" "AVA_DESKTOP_WEBSOCKET_PORT"

require_contains "${RUNTIME_MANIFEST}" "export const RUNTIME_MANIFEST_NAME = 'ava-runtime-manifest.json'"
require_contains "${RUNTIME_MANIFEST}" "export function readRuntimeManifestRepoRoot"

require_contains "${BUILD_SCRIPT}" "function findCachedElectronZipDir(cacheRoot, version"
require_contains "${BUILD_SCRIPT}" "--electron-zip-dir="
require_contains "${BUILD_SCRIPT}" "--download.cacheRoot"
require_contains "${BUILD_SCRIPT}" "--extra-resource="
require_contains "${BUILD_SCRIPT}" "invalid runtime manifest repoRoot"

require_contains "${PRELOAD}" "contextBridge.exposeInMainWorld('avaDesktop', api)"
require_contains "${PRELOAD}" "setNanobotRoot"
require_contains "${PRELOAD}" "retryCore"
require_contains "${PRELOAD}" "cancelBootstrap"
require_contains "${PRELOAD}" "onBootstrapState"

require_contains "${SETUP}" "Ava Setup"
require_contains "${SETUP}" "Select Nanobot"
require_contains "${SETUP}" "window.avaDesktop?.onBootstrapState"
require_contains "${SETUP}" "window.avaDesktop.setNanobotRoot"
require_contains "${SETUP}" "window.avaDesktop.retryCore"
require_contains "${SETUP}" "window.avaDesktop.cancelBootstrap"
require_contains "${SETUP}" "window.avaDesktop.openLogs"

ASAR_STRINGS="$(mktemp "${TMPDIR:-/tmp}/ava-app-asar.XXXXXX")"
trap 'rm -f "${ASAR_STRINGS}"' EXIT
LC_ALL=C strings "${APP_ASAR}" >"${ASAR_STRINGS}"

require_contains "${ASAR_STRINGS}" "setup.html"
require_contains "${ASAR_STRINGS}" "const CORE_HEALTH_TIMEOUT_MS = 120_000"
require_contains "${ASAR_STRINGS}" "Ava Setup"
require_contains "${ASAR_STRINGS}" "window.avaDesktop.cancelBootstrap"
require_contains "${ASAR_STRINGS}" "desktop-config.mjs"
require_contains "${ASAR_STRINGS}" "export function saveNanobotRoot"
require_contains "${ASAR_STRINGS}" "launch-env.mjs"
require_contains "${ASAR_STRINGS}" "runtime-manifest.mjs"
require_contains "${ASAR_STRINGS}" "runtime-mirror.mjs"
require_contains "${ASAR_STRINGS}" "export function resolveLaunchPath"
require_contains "${ASAR_STRINGS}" "readRuntimeManifestRepoRoot"
require_contains "${ASAR_STRINGS}" "AVA_DESKTOP_CONSOLE_PORT: String(config.port)"
require_contains "${ASAR_STRINGS}" "AVA_DESKTOP_GATEWAY_PORT"
require_contains "${ASAR_STRINGS}" "AVA_DESKTOP_WEBSOCKET_PORT"
require_contains "${ASAR_STRINGS}" "prepareRuntimeMirror"
require_contains "${ASAR_STRINGS}" "runtime-mirror"
require_contains "${ASAR_STRINGS}" "const pythonPath = fs.realpathSync(venvPythonPath)"
require_contains "${ASAR_STRINGS}" "spawn(pythonPath, ['-m', 'ava', 'gateway']"
require_contains "${ASAR_STRINGS}" "export function venvSitePackages(repoRoot, pythonExecutable = '')"
require_contains "${ASAR_STRINGS}" "VIRTUAL_ENV: path.join(config.repoRoot, '.venv')"
require_contains "${ASAR_STRINGS}" "export function httpGetStatus(url, timeoutMs = 2_000)"
require_contains "${ASAR_STRINGS}" "async function checkStartupInterfaces(config)"
require_contains "${ASAR_STRINGS}" "/api/auth/me"
require_contains "${ASAR_STRINGS}" "Ava auth interface returned HTTP"
require_contains "${ASAR_STRINGS}" "core_startup_timeout"
require_contains "${ASAR_STRINGS}" "Ava core did not become reachable within"
require_contains "${PACKAGED_RUNTIME_MANIFEST}" '"repoRoot"'
require_contains "${ASAR_STRINGS}" "ava:cancelBootstrap"
require_contains "${ASAR_STRINGS}" "setup surface did not finish loading within"
require_contains "${ASAR_STRINGS}" "dialog.showErrorBox('Ava setup failed to load'"
require_contains "${ASAR_STRINGS}" "function showFatalStartupError(error)"
require_contains "${ASAR_STRINGS}" "dialog.showErrorBox('Ava startup failed'"
require_contains "${ASAR_STRINGS}" ".catch(showFatalStartupError)"
require_contains "${ASAR_STRINGS}" "active.child.kill('SIGKILL')"
require_contains "${ASAR_STRINGS}" "await stopAvaCore();"
require_contains "${ASAR_STRINGS}" "avaCoreProcess = null;"
require_contains "${ASAR_STRINGS}" "label: 'Open Logs'"
require_contains "${ASAR_STRINGS}" "label: 'Retry Core'"
require_contains "${ASAR_STRINGS}" "label: 'Show Window'"
require_contains "${ASAR_STRINGS}" "label: 'Edit'"
require_contains "${ASAR_STRINGS}" "label: 'View'"
require_contains "${ASAR_STRINGS}" "label: 'Window'"
require_contains "${ASAR_STRINGS}" "role: 'close'"
require_contains "${ASAR_STRINGS}" "Menu.setApplicationMenu(menu)"
require_contains "${ASAR_STRINGS}" "function ensureForegroundActivation()"
require_contains "${ASAR_STRINGS}" "app.setActivationPolicy('regular')"
require_contains "${ASAR_STRINGS}" "app.dock?.show?.()"
require_contains "${ASAR_STRINGS}" "function presentMainWindow(appWindow, reason)"
require_contains "${ASAR_STRINGS}" "appWindow.setSkipTaskbar(false)"
require_contains "${ASAR_STRINGS}" "appWindow.moveTop()"
require_contains "${ASAR_STRINGS}" "app.focus({ steal: true })"
require_contains "${ASAR_STRINGS}" "app.commandLine.appendSwitch('use-mock-keychain')"
require_contains "${ASAR_STRINGS}" "show: false"
require_contains "${ASAR_STRINGS}" "focusable: true"
require_contains "${ASAR_STRINGS}" "function createBootstrapWindow(config, { loadSetup = true } = {})"
require_contains "${ASAR_STRINGS}" "if (!loadSetup)"
require_contains "${ASAR_STRINGS}" "createBootstrapWindow(config, { loadSetup: !consoleLoaded })"
require_contains "${ASAR_STRINGS}" "presentMainWindow(mainWindow, 'setup loaded')"
require_contains "${ASAR_STRINGS}" 'presentMainWindow(mainWindow, `console loaded: ${reason}`)'
require_contains "${ASAR_STRINGS}" "await showMainWindow();"
require_contains "${ASAR_STRINGS}" "const TRAY_ICON_SIZE = 18;"
require_contains "${ASAR_STRINGS}" "image.resize({ width: TRAY_ICON_SIZE, height: TRAY_ICON_SIZE })"
require_contains "${ASAR_STRINGS}" "new Tray(trayImage)"
require_contains "${ASAR_STRINGS}" "globalShortcut.register('Control+Shift+A'"
require_contains "${ASAR_STRINGS}" "globalShortcut.unregisterAll()"
require_contains "${ASAR_STRINGS}" "ava:setBadgeCount"
require_contains "${ASAR_STRINGS}" "invalid badge count"
require_contains "${ASAR_STRINGS}" "scheduleUpdateChecks();"
require_contains "${ASAR_STRINGS}" "const UPDATE_CHECK_INITIAL_DELAY_MS = 5 * 1000;"
require_contains "${ASAR_STRINGS}" "update check failed:"
require_contains "${ASAR_STRINGS}" "update notification shown for"
require_contains "${ASAR_STRINGS}" "electron/lib/update-check.mjs"
require_contains "${ASAR_STRINGS}" "DEFAULT_UPDATE_REPO = 'linziyanleo/ava'"
require_contains "${ASAR_STRINGS}" "GITHUB_TOKEN"
require_contains "${ASAR_STRINGS}" "GH_TOKEN"
require_contains "${ASAR_STRINGS}" "if (process.platform !== 'darwin')"
require_contains "${ASAR_STRINGS}" "app.on('activate', () => {"
require_contains "${ASAR_STRINGS}" "const RING_BUFFER_BYTES = 256 * 1024"
require_contains "${ASAR_STRINGS}" "function appendRingBuffer(buffer, chunk, maxBytes = RING_BUFFER_BYTES)"
require_contains "${ASAR_STRINGS}" "stderrTail = appendRingBuffer(stderrTail, chunk)"
require_contains "${ASAR_STRINGS}" "detailParts.join('\\n\\n').slice(0, RING_BUFFER_BYTES)"
require_contains "${ASAR_STRINGS}" "buttons: ['Retry', 'Pick nanobot', 'Open logs', 'Quit']"

echo "Desktop setup surface is wired and packaged in ${APP_PATH}"
